Misc template fixes
w3c/markup-validator pull request #85
Opened 2024-02-27 10:42 UTC by deniak

* fixes logo in headers
* update copyright

2024-02-27 23:30 UTC, vivienlacourba requested changes

2024-02-27 23:30 UTC, vivienlacourba commented on share/templates/en_US/footer.tmpl
> +    <a href="https://www.w3.org/Status" title="W3C's Open Source, bringing you free Web quality tools and more"><img src="https://www.w3.org/assets/logos/w3c/w3c-no-bars.svg" alt="W3C" width="72" hei
I saw you replaced `./` by `/` in all URI prefix, do you want to do the same for `./images/opensource-55x48.png` 

```suggestion
    <a href="https://www.w3.org/Status" title="W3C's Open Source, bringing you free Web quality tools and more"><img src="https://www.w3.org/assets/logos/w3c/w3c-no-bars.svg" alt="W3C" width="72" height="47"><img src="/images/opensource-55x48.png" alt="Open-Source" title="We are building certified Open Source/Free Software. - see www.opensource.org" width="55" height="48"></a>
```

2024-02-27 23:30 UTC, vivienlacourba commented on htdocs/header.html
> +          <img alt="W3C Logo" width="110" height="61" id="logo" src="<!--#echo var="relroot" -->images/w3c.png" />
I think using `images/no_w3c.png` was on purpose, so if someone wanted to run this service on its own server it would not include the W3C and not be advertised as a service from W3C.

See the related `w3c` `Makefile`rule:
https://github.com/w3c/markup-validator/blob/e6ed8784e91c6a60112d794be7d3fcf526dda59e/Makefile#L66-L69

2024-02-28 06:56 UTC, deniak commented on htdocs/header.html
> +          <img alt="W3C Logo" width="110" height="61" id="logo" src="<!--#echo var="relroot" -->images/w3c.png" />
Good catch. I don't think it's great to have these files updated locally so I went with another option (https://github.com/w3c/markup-validator/pull/85/commits/82498823baae2e15f3e44a34201972cff3d20ad2)
With this method, we only need to add an environment variable `ENV=w3.org` (in the apache config) and the template will take care of using the right logo.

2024-02-28 13:47 UTC, vivienlacourba approved these changes

2024-02-28 13:51 UTC, merged